# Ansible runs tasks on the local machine, no SSH needed

[masters]
localhost ansible_connection=local

[workers]
localhost ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3